name: build
on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 最大化构建环境
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: 1.准备环境
        run: |
          sudo apt install aria2 python3 busybox zip tar apktool unzip p7zip-full openjdk-8-jre zipalign zstd bc android-sdk-libsparse-utils repo -y
          sudo apt --fix-broken install -y
          sudo apt update --fix-missing -y
      - name: 2.克隆仓库
        run: |
          repo init -u https://github.com/PixelExperience/manifest -b fourteen
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          ./build/envsetup.sh
          lunch aosp_atom-userdebug
          mka bacon -jX
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 1
          path: /home/runner/work
          warn: Output a warning but do not fail the action
          error: Fail the action with an error message
          ignore: Do not output any warnings or errors, the action does not fail
          if-no-files-found: warn
          retention-days: 9
          
      - name: 5.上传移植LOG
        uses: actions/upload-artifact@v4
        with:
          name: HyperOS-PortLOG
          path: "/home/runner/work/HyperOS_Action_builder/HyperOS_Action_builder/hyperos_port/HyperOS_portlog.log"
          compression-level: 9
